export type InsightMixedLanguage = "is" | "en" | "pl" | "sr";

function language(value: string | null | undefined): InsightMixedLanguage {
  if (value === "en" || value === "pl" || value === "sr") return value;
  return "is";
}

const copy = {
  is: {
    title: "Ný Innsýn",
    subtitle: "Blönduð stjórnendasýn úr rekjanlegum gögnum",
    back: "Núverandi Innsýn",
    mixed: "Blönduð",
    visual: "Myndræn",
    numbers: "Tölur",
    explanation: "Skýring",
    next: "næst",
    period: "Tímabil",
    last12: "Síðustu 12 mánuðir",
    thisYear: "Þetta ár",
    thisQuarter: "Þessi ársfjórðungur",
    thisMonth: "Þessi mánuður",
    comparison: "Borið saman við fyrra sambærilegt tímabil",
    booked: "Bókað",
    known: "Þekkt",
    pending: "Bíður staðfestingar",
    standing: "Svona stendur reksturinn",
    bookedResultPositive: (value: string) => `Bókuð niðurstaða tímabilsins er jákvæð um ${value}.`,
    bookedResultNegative: (value: string) => `Bókuð niðurstaða tímabilsins er neikvæð um ${value}.`,
    revenueChanged: (direction: string, percent: string) => `Bókaðar tekjur ${direction} um ${percent} miðað við samanburðartímabilið.`,
    expensesChanged: (direction: string, percent: string) => `Bókuð rekstrargjöld ${direction} um ${percent} miðað við samanburðartímabilið.`,
    rose: "jukust",
    fell: "lækkuðu",
    cardPending: (count: number, amount: string) => `${count} kortafærslur, samtals ${amount}, bíða afstemmingar.`,
    bankPending: (count: number, amount: string) => `${count} bankafærslur, samtals ${amount}, eru óafstemmdar.`,
    noComparison: "Sambærileg bókuð gögn fundust ekki fyrir fyrra tímabilið; breytingar eru því ekki prósentureiknaðar.",
    development: "Þróun",
    developmentHelp: "Bókaðar tekjur, rekstrargjöld og niðurstaða eftir mánuðum, ásamt stjórnendalegri trendlínu.",
    operatingTrend: "Rekstrarþróun (3 mán.)",
    operatingTrendHelp: "Rekstrarþróun er 3 mánaða hlaupandi meðaltal af bókaðri niðurstöðu. Hún jafnar tímaskekkju þegar reikningar koma á óreglulegum dagsetningum en breytir ekki bókuðum staðreyndum.",
    unitPrices: "Einingarverð",
    unitPricesHelp: "Þróun úr magni, mælieiningu og verði í varðveittum vörulínum. Útreikningurinn er deterministic og kallar ekki á nýtt AI.",
    unitPriceKnown: "Þekkt/reiknað úr vörulínum",
    latestUnitPrice: "Nýjasta verð",
    lastKnownUnitPrice: "Síðasta þekkta verð",
    averageUnitPrice: "Magnvegið meðalverð",
    totalQuantity: "Heildarmagn",
    totalUnitCost: "Heildarkostnaður",
    monthlyUnitUsage: "Magn og kostnaður eftir mánuðum",
    monthlyUnitUsageHelp: "Mánaðarlegt magn, línukostnaður og magnvegið meðalverð úr sömu rekjanlegu vörulínum.",
    costDrivers: "Hvað breyttist og af hverju?",
    costDriversHelp: "Nýjasti samfelldi mánaðarsamanburðurinn sundurgreinir kostnaðarbreytingu í magnáhrif og verðáhrif án AI.",
    costDriversPeriod: (from: string, to: string) => `${from} → ${to}`,
    costChange: "Kostnaðarbreyting",
    quantityEffect: "Magnáhrif",
    priceEffect: "Verðáhrif",
    quantityChange: "Breyting á magni",
    unitPriceChange: "Breyting á meðalverði",
    costDriversExactNote: "Magnáhrif og verðáhrif eru reiknuð samhverft svo þau leggjast nákvæmlega saman í kostnaðarbreytinguna. Bókhaldi og vörulínum er ekki breytt.",
    noCostDriverComparison: "Engir tveir samfelldir mánuðir með nægum gögnum fundust enn.",
    unitPriceObservations: "mælingar",
    unitPriceDateCount: "Dagsetningar",
    unitPriceLineCount: "Línur",
    unitPriceSingleDate: "Ein staðfest dagsetning · engin verðþróun reiknuð enn.",
    unitPriceNoHistory: "Einingarverðsgögn fundust en ekki næg endurtekning er komin til að sýna verðþróun enn.",
    unitPriceNoData: "Engar vörulínur með nægu magni, mælieiningu og verði fundust á tímabilinu.",
    unitPriceSourceNote: "Innsýn notar varðveitt vörulínugögn og deterministic stærðfræði, aldrei nýtt AI-kall. Fyrir eldri, skýrar eldsneytislínur má endurheimta lítra úr prentuðu einingarverði og línuheild aðeins þegar útreikningurinn stemmir innan námundunarvikmarks. Margar línur sama dag teljast einn tímapunktur.",
    openUnitPriceAnalysis: "Kafa dýpra",
    unitPriceDrilldown: "Einingarverð · rekjanleiki",
    minimumUnitPrice: "Lægsta verð",
    maximumUnitPrice: "Hæsta verð",
    date: "Dagsetning",
    merchant: "Seljandi",
    quantity: "Magn",
    unitPrice: "Einingarverð",
    lineTotal: "Línuheild",
    printedUnitPrice: "Prentað/geymt einingarverð",
    derivedUnitPrice: "Reiknað úr línuheild og magni",
    revenue: "Tekjur",
    expenses: "Rekstrargjöld",
    result: "Niðurstaða",
    whereMoney: "Hvert fara peningarnir?",
    accountsHelp: "Stærstu bókuðu gjaldalyklarnir á tímabilinu.",
    vendors: "Stærstu mótaðilar",
    vendorsHelp: "Seljendur sem mynda stærstan bókaðan rekstrarkostnað.",
    documents: "skjöl",
    dataAndReconciliation: "Gögn og afstemming",
    bookedDocuments: "Bókuð fylgiskjöl",
    bankTransactions: "Bankafærslur",
    cardTransactions: "Kortafærslur",
    noBank: "Engar bankafærslur fundust á tímabilinu.",
    noCards: "Engar kortafærslur fundust á tímabilinu.",
    bankFlow: "Nettó bankahreyfing",
    bankUnreconciled: "Óafstemmt í banka",
    cardPurchases: "Kortakaup",
    cardCredits: "Kortainneignir/endurgreiðslur",
    cardCoverage: "Afstemmingarhlutfall korta",
    evidenceNote: "Bókhaldstölur eru aðeins úr bókuðum gögnum. Banka- og kortafærslur eru sýndar sérstaklega og verða ekki bókhaldsstaðreyndir án staðfestingar.",
    testing: "Prófunarsýn v1",
    testingHelp: "Þessi sýn er byggð samhliða núverandi Innsýn svo hægt sé að sannreyna tölur og upplifun áður en hún tekur yfir aðalsíðuna.",
    noExpenses: "Engin bókuð rekstrargjöld fundust á tímabilinu.",
    openCurrent: "Opna núverandi djúpgreiningu",
    openAnalysis: "Kafa dýpra",
    drilldown: "Sundurliðun",
    closeAnalysis: "Loka sundurliðun",
    netBooked: "Bókað nettó",
    monthlyBreakdown: "Þróun eftir mánuðum",
    breakdownMerchants: "Mótaðilar sem mynda upphæðina",
    breakdownAccounts: "Gjaldalyklar sem mynda upphæðina",
    sourceDocuments: "Fylgiskjölin á bak við töluna",
    sourceDocumentsHelp: "Hver lína er rekjanleg niður í bókað fylgiskjal og frumgagn.",
    voucher: "Fylgiskjal nr.",
    noVoucher: "Fylgiskjalsnúmer ekki tiltækt",
    openDocument: "Opna fylgiskjal",
  },
  en: {
    title: "New Insights",
    subtitle: "Mixed management view from traceable data",
    back: "Current Insights",
    mixed: "Mixed",
    visual: "Visual",
    numbers: "Numbers",
    explanation: "Explanation",
    next: "next",
    period: "Period",
    last12: "Last 12 months",
    thisYear: "This year",
    thisQuarter: "This quarter",
    thisMonth: "This month",
    comparison: "Compared with the previous comparable period",
    booked: "Booked",
    known: "Known",
    pending: "Pending confirmation",
    standing: "How the business stands",
    bookedResultPositive: (value: string) => `The booked result for the period is positive by ${value}.`,
    bookedResultNegative: (value: string) => `The booked result for the period is negative by ${value}.`,
    revenueChanged: (direction: string, percent: string) => `Booked revenue ${direction} by ${percent} compared with the comparison period.`,
    expensesChanged: (direction: string, percent: string) => `Booked operating expenses ${direction} by ${percent} compared with the comparison period.`,
    rose: "increased",
    fell: "decreased",
    cardPending: (count: number, amount: string) => `${count} card transactions, totaling ${amount}, are awaiting reconciliation.`,
    bankPending: (count: number, amount: string) => `${count} bank transactions, totaling ${amount}, are unreconciled.`,
    noComparison: "No comparable booked data was found for the previous period, so percentage changes are not calculated.",
    development: "Trend",
    developmentHelp: "Booked revenue, operating expenses and result by month, with a management trend line.",
    operatingTrend: "Operating trend (3 mo.)",
    operatingTrendHelp: "The operating trend is a 3-month rolling average of the booked result. It reduces timing noise when invoices arrive on irregular dates without changing booked facts.",
    unitPrices: "Unit prices",
    unitPricesHelp: "Trends from quantity, unit and price stored on purchase lines. The calculation is deterministic and makes no new AI call.",
    unitPriceKnown: "Known/calculated from line items",
    latestUnitPrice: "Latest price",
    lastKnownUnitPrice: "Last known price",
    averageUnitPrice: "Quantity-weighted average",
    totalQuantity: "Total quantity",
    totalUnitCost: "Total cost",
    monthlyUnitUsage: "Quantity and cost by month",
    monthlyUnitUsageHelp: "Monthly quantity, line-item cost and quantity-weighted average price from the same traceable purchase lines.",
    costDrivers: "What changed and why?",
    costDriversHelp: "The latest consecutive-month comparison decomposes the cost change into quantity and price effects without AI.",
    costDriversPeriod: (from: string, to: string) => `${from} → ${to}`,
    costChange: "Cost change",
    quantityEffect: "Quantity effect",
    priceEffect: "Price effect",
    quantityChange: "Quantity change",
    unitPriceChange: "Average price change",
    costDriversExactNote: "Quantity and price effects use a symmetric calculation so they add exactly to the cost change. No accounting or line-item fact is changed.",
    noCostDriverComparison: "No two consecutive months with sufficient data were found yet.",
    unitPriceObservations: "observations",
    unitPriceDateCount: "Dates",
    unitPriceLineCount: "Lines",
    unitPriceSingleDate: "One confirmed date · no price trend is calculated yet.",
    unitPriceNoHistory: "Unit-price data was found, but there are not enough repeated observations to show a trend yet.",
    unitPriceNoData: "No line items with sufficient quantity, unit and price data were found in the period.",
    unitPriceSourceNote: "Insights uses stored line-item facts and deterministic arithmetic, never a new AI call. For older unambiguous fuel rows, litres may be reconstructed from the printed unit price and line total only when the arithmetic matches within a rounding tolerance. Multiple lines on the same day count as one time point.",
    openUnitPriceAnalysis: "Drill down",
    unitPriceDrilldown: "Unit price · traceability",
    minimumUnitPrice: "Lowest price",
    maximumUnitPrice: "Highest price",
    date: "Date",
    merchant: "Merchant",
    quantity: "Quantity",
    unitPrice: "Unit price",
    lineTotal: "Line total",
    printedUnitPrice: "Printed/stored unit price",
    derivedUnitPrice: "Calculated from line total and quantity",
    revenue: "Revenue",
    expenses: "Operating expenses",
    result: "Result",
    whereMoney: "Where does the money go?",
    accountsHelp: "Largest booked expense accounts in the period.",
    vendors: "Largest counterparties",
    vendorsHelp: "Vendors representing the largest booked operating expenses.",
    documents: "documents",
    dataAndReconciliation: "Data and reconciliation",
    bookedDocuments: "Booked documents",
    bankTransactions: "Bank transactions",
    cardTransactions: "Card transactions",
    noBank: "No bank transactions were found in the period.",
    noCards: "No card transactions were found in the period.",
    bankFlow: "Net bank movement",
    bankUnreconciled: "Unreconciled bank activity",
    cardPurchases: "Card purchases",
    cardCredits: "Card credits/refunds",
    cardCoverage: "Card reconciliation coverage",
    evidenceNote: "Accounting figures contain booked data only. Bank and card activity is shown separately and does not become an accounting fact without confirmation.",
    testing: "Test view v1",
    testingHelp: "This view is being built alongside the current Insights page so figures and usability can be verified before it replaces the main view.",
    noExpenses: "No booked operating expenses were found in the period.",
    openCurrent: "Open current deep analysis",
    openAnalysis: "Drill down",
    drilldown: "Breakdown",
    closeAnalysis: "Close breakdown",
    netBooked: "Net booked",
    monthlyBreakdown: "Trend by month",
    breakdownMerchants: "Counterparties behind the amount",
    breakdownAccounts: "Expense accounts behind the amount",
    sourceDocuments: "Documents behind the figure",
    sourceDocumentsHelp: "Each row can be traced to the booked document and original source.",
    voucher: "Voucher no.",
    noVoucher: "Voucher number unavailable",
    openDocument: "Open document",
  },
  pl: {
    title: "Nowe Analizy",
    subtitle: "Mieszany widok zarządczy z danych możliwych do prześledzenia",
    back: "Obecne Analizy",
    mixed: "Mieszany",
    visual: "Wizualny",
    numbers: "Liczby",
    explanation: "Wyjaśnienie",
    next: "następnie",
    period: "Okres",
    last12: "Ostatnie 12 miesięcy",
    thisYear: "Ten rok",
    thisQuarter: "Ten kwartał",
    thisMonth: "Ten miesiąc",
    comparison: "Porównanie z poprzednim porównywalnym okresem",
    booked: "Zaksięgowane",
    known: "Znane",
    pending: "Oczekuje na potwierdzenie",
    standing: "Tak wygląda sytuacja firmy",
    bookedResultPositive: (value: string) => `Zaksięgowany wynik okresu jest dodatni o ${value}.`,
    bookedResultNegative: (value: string) => `Zaksięgowany wynik okresu jest ujemny o ${value}.`,
    revenueChanged: (direction: string, percent: string) => `Zaksięgowane przychody ${direction} o ${percent} względem okresu porównawczego.`,
    expensesChanged: (direction: string, percent: string) => `Zaksięgowane koszty operacyjne ${direction} o ${percent} względem okresu porównawczego.`,
    rose: "wzrosły",
    fell: "spadły",
    cardPending: (count: number, amount: string) => `${count} transakcji kartowych o łącznej wartości ${amount} oczekuje na uzgodnienie.`,
    bankPending: (count: number, amount: string) => `${count} transakcji bankowych o łącznej wartości ${amount} pozostaje nieuzgodnionych.`,
    noComparison: "Nie znaleziono porównywalnych zaksięgowanych danych za poprzedni okres, dlatego zmiany procentowe nie są obliczane.",
    development: "Trend",
    developmentHelp: "Zaksięgowane przychody, koszty operacyjne i wynik według miesięcy wraz z linią trendu zarządczego.",
    operatingTrend: "Trend operacyjny (3 mies.)",
    operatingTrendHelp: "Trend operacyjny to 3-miesięczna średnia krocząca zaksięgowanego wyniku. Ogranicza wpływ nieregularnych dat faktur bez zmiany zaksięgowanych faktów.",
    unitPrices: "Ceny jednostkowe",
    unitPricesHelp: "Trend z ilości, jednostki i ceny zapisanych w pozycjach dokumentu. Obliczenie jest deterministyczne i nie wywołuje nowej analizy AI.",
    unitPriceKnown: "Znane/obliczone z pozycji",
    latestUnitPrice: "Najnowsza cena",
    lastKnownUnitPrice: "Ostatnia znana cena",
    averageUnitPrice: "Średnia ważona ilością",
    totalQuantity: "Łączna ilość",
    totalUnitCost: "Łączny koszt",
    monthlyUnitUsage: "Ilość i koszt według miesięcy",
    monthlyUnitUsageHelp: "Miesięczna ilość, koszt pozycji i średnia cena ważona ilością z tych samych możliwych do prześledzenia pozycji.",
    costDrivers: "Co się zmieniło i dlaczego?",
    costDriversHelp: "Najnowsze porównanie kolejnych miesięcy rozkłada zmianę kosztu na efekt ilości i ceny bez AI.",
    costDriversPeriod: (from: string, to: string) => `${from} → ${to}`,
    costChange: "Zmiana kosztu",
    quantityEffect: "Efekt ilości",
    priceEffect: "Efekt ceny",
    quantityChange: "Zmiana ilości",
    unitPriceChange: "Zmiana średniej ceny",
    costDriversExactNote: "Efekty ilości i ceny są liczone symetrycznie, dzięki czemu dokładnie sumują się do zmiany kosztu. Księgowanie i dane pozycji pozostają bez zmian.",
    noCostDriverComparison: "Nie znaleziono jeszcze dwóch kolejnych miesięcy z wystarczającymi danymi.",
    unitPriceObservations: "pomiarów",
    unitPriceDateCount: "Daty",
    unitPriceLineCount: "Pozycje",
    unitPriceSingleDate: "Jedna potwierdzona data · trend cenowy nie jest jeszcze obliczany.",
    unitPriceNoHistory: "Znaleziono dane o cenach jednostkowych, ale nie ma jeszcze wystarczającej liczby powtórzeń, aby pokazać trend.",
    unitPriceNoData: "W okresie nie znaleziono pozycji z wystarczającymi danymi o ilości, jednostce i cenie.",
    unitPriceSourceNote: "Analizy używają zapisanych danych pozycji i deterministycznych obliczeń, bez nowego wywołania AI. Dla starszych, jednoznacznych pozycji paliwowych litry mogą być odtworzone z wydrukowanej ceny jednostkowej i sumy pozycji tylko wtedy, gdy obliczenie mieści się w tolerancji zaokrąglenia. Wiele pozycji tego samego dnia liczy się jako jeden punkt w czasie.",
    openUnitPriceAnalysis: "Pokaż szczegóły",
    unitPriceDrilldown: "Cena jednostkowa · śledzenie",
    minimumUnitPrice: "Najniższa cena",
    maximumUnitPrice: "Najwyższa cena",
    date: "Data",
    merchant: "Sprzedawca",
    quantity: "Ilość",
    unitPrice: "Cena jednostkowa",
    lineTotal: "Suma pozycji",
    printedUnitPrice: "Wydrukowana/zapisana cena jednostkowa",
    derivedUnitPrice: "Obliczona z sumy pozycji i ilości",
    revenue: "Przychody",
    expenses: "Koszty operacyjne",
    result: "Wynik",
    whereMoney: "Dokąd trafiają pieniądze?",
    accountsHelp: "Największe zaksięgowane konta kosztowe w okresie.",
    vendors: "Najwięksi kontrahenci",
    vendorsHelp: "Sprzedawcy tworzący największe zaksięgowane koszty operacyjne.",
    documents: "dokumentów",
    dataAndReconciliation: "Dane i uzgodnienie",
    bookedDocuments: "Zaksięgowane dokumenty",
    bankTransactions: "Transakcje bankowe",
    cardTransactions: "Transakcje kartowe",
    noBank: "Brak transakcji bankowych w tym okresie.",
    noCards: "Brak transakcji kartowych w tym okresie.",
    bankFlow: "Przepływ netto na rachunkach",
    bankUnreconciled: "Nieuzgodnione w banku",
    cardPurchases: "Zakupy kartą",
    cardCredits: "Zwroty/uznania kartowe",
    cardCoverage: "Pokrycie uzgodnienia kart",
    evidenceNote: "Kwoty księgowe obejmują wyłącznie dane zaksięgowane. Dane bankowe i kartowe są pokazywane oddzielnie i bez potwierdzenia nie stają się faktem księgowym.",
    testing: "Widok testowy v1",
    testingHelp: "Widok powstaje równolegle z obecną stroną Analiz, aby przed zastąpieniem głównego widoku można było sprawdzić liczby i użyteczność.",
    noExpenses: "Brak zaksięgowanych kosztów operacyjnych w tym okresie.",
    openCurrent: "Otwórz obecną analizę szczegółową",
    openAnalysis: "Pokaż szczegóły",
    drilldown: "Szczegóły",
    closeAnalysis: "Zamknij szczegóły",
    netBooked: "Zaksięgowane netto",
    monthlyBreakdown: "Przebieg miesięczny",
    breakdownMerchants: "Kontrahenci tworzący kwotę",
    breakdownAccounts: "Konta kosztowe tworzące kwotę",
    sourceDocuments: "Dokumenty stojące za kwotą",
    sourceDocumentsHelp: "Każdy wiersz można prześledzić do zaksięgowanego dokumentu i źródła.",
    voucher: "Nr dokumentu",
    noVoucher: "Brak numeru dokumentu",
    openDocument: "Otwórz dokument",
  },
  sr: {
    title: "Нови Увиди",
    subtitle: "Комбиновани управљачки приказ из проверљивих података",
    back: "Тренутни Увиди",
    mixed: "Комбиновано",
    visual: "Визуелно",
    numbers: "Бројеви",
    explanation: "Објашњење",
    next: "следеће",
    period: "Период",
    last12: "Последњих 12 месеци",
    thisYear: "Ова година",
    thisQuarter: "Овај квартал",
    thisMonth: "Овај месец",
    comparison: "Упоређено са претходним упоредивим периодом",
    booked: "Књижено",
    known: "Познато",
    pending: "Чека потврду",
    standing: "Овако стоји пословање",
    bookedResultPositive: (value: string) => `Књижени резултат периода је позитиван за ${value}.`,
    bookedResultNegative: (value: string) => `Књижени резултат периода је негативан за ${value}.`,
    revenueChanged: (direction: string, percent: string) => `Књижени приходи су ${direction} за ${percent} у односу на упоредни период.`,
    expensesChanged: (direction: string, percent: string) => `Књижени пословни расходи су ${direction} за ${percent} у односу на упоредни период.`,
    rose: "порасли",
    fell: "смањени",
    cardPending: (count: number, amount: string) => `${count} картичних трансакција, укупно ${amount}, чека усаглашавање.`,
    bankPending: (count: number, amount: string) => `${count} банковних трансакција, укупно ${amount}, није усаглашено.`,
    noComparison: "Нису пронађени упоредиви књижени подаци за претходни период, па се процентуалне промене не рачунају.",
    development: "Кретање",
    developmentHelp: "Књижени приходи, пословни расходи и резултат по месецима, уз управљачку линију тренда.",
    operatingTrend: "Пословни тренд (3 мес.)",
    operatingTrendHelp: "Пословни тренд је тромесечни покретни просек књиженог резултата. Ублажава временску неравномерност фактура без измене књижених чињеница.",
    unitPrices: "Јединичне цене",
    unitPricesHelp: "Кретање из количине, јединице и цене сачуваних на ставкама документа. Обрачун је детерминистички и не покреће нови AI позив.",
    unitPriceKnown: "Познато/израчунато из ставки",
    latestUnitPrice: "Најновија цена",
    lastKnownUnitPrice: "Последња позната цена",
    averageUnitPrice: "Просек пондерисан количином",
    totalQuantity: "Укупна количина",
    totalUnitCost: "Укупан трошак",
    monthlyUnitUsage: "Количина и трошак по месецима",
    monthlyUnitUsageHelp: "Месечна количина, трошак ставки и просечна цена пондерисана количином из истих следљивих ставки.",
    costDrivers: "Шта се променило и зашто?",
    costDriversHelp: "Најновије поређење узастопних месеци раздваја промену трошка на утицај количине и цене без AI.",
    costDriversPeriod: (from: string, to: string) => `${from} → ${to}`,
    costChange: "Промена трошка",
    quantityEffect: "Утицај количине",
    priceEffect: "Утицај цене",
    quantityChange: "Промена количине",
    unitPriceChange: "Промена просечне цене",
    costDriversExactNote: "Утицаји количине и цене рачунају се симетрично тако да се тачно сабирају у промену трошка. Књижење и подаци ставки се не мењају.",
    noCostDriverComparison: "Још нису пронађена два узастопна месеца са довољно података.",
    unitPriceObservations: "мерења",
    unitPriceDateCount: "Датуми",
    unitPriceLineCount: "Ставке",
    unitPriceSingleDate: "Један потврђен датум · тренд цене се још не израчунава.",
    unitPriceNoHistory: "Подаци о јединичним ценама постоје, али још нема довољно поновљених мерења за тренд.",
    unitPriceNoData: "У периоду нема ставки са довољним подацима о количини, јединици и цени.",
    unitPriceSourceNote: "Увиди користе сачуване податке ставки и детерминистичку математику, без новог AI позива. За старије, недвосмислене ставке горива литри се могу реконструисати из одштампане јединичне цене и укупне вредности ставке само када се прорачун поклапа унутар толеранције заокруживања. Више ставки истог дана рачуна се као једна временска тачка.",
    openUnitPriceAnalysis: "Прикажи детаље",
    unitPriceDrilldown: "Јединична цена · следљивост",
    minimumUnitPrice: "Најнижа цена",
    maximumUnitPrice: "Највиша цена",
    date: "Датум",
    merchant: "Добављач",
    quantity: "Количина",
    unitPrice: "Јединична цена",
    lineTotal: "Укупно ставка",
    printedUnitPrice: "Одштампана/сачувана јединична цена",
    derivedUnitPrice: "Израчунато из укупне ставке и количине",
    revenue: "Приходи",
    expenses: "Пословни расходи",
    result: "Резултат",
    whereMoney: "Где одлази новац?",
    accountsHelp: "Највећи књижени расходни конти у периоду.",
    vendors: "Највеће друге стране",
    vendorsHelp: "Добављачи који чине највеће књижене пословне расходе.",
    documents: "докумената",
    dataAndReconciliation: "Подаци и усаглашавање",
    bookedDocuments: "Књижени документи",
    bankTransactions: "Банковне трансакције",
    cardTransactions: "Картичне трансакције",
    noBank: "Нема банковних трансакција у периоду.",
    noCards: "Нема картичних трансакција у периоду.",
    bankFlow: "Нето кретање у банци",
    bankUnreconciled: "Неусаглашено у банци",
    cardPurchases: "Картичне куповине",
    cardCredits: "Картична одобрења/повраћаји",
    cardCoverage: "Покривеност усаглашавања картица",
    evidenceNote: "Књиговодствене вредности садрже само књижене податке. Банковне и картичне трансакције се приказују одвојено и без потврде не постају књиговодствена чињеница.",
    testing: "Пробни приказ v1",
    testingHelp: "Овај приказ се гради паралелно са тренутним Увидима како би се бројке и употребљивост провериле пре него што замени главни приказ.",
    noExpenses: "Нема књижених пословних расхода у периоду.",
    openCurrent: "Отвори тренутну дубинску анализу",
    openAnalysis: "Прикажи детаље",
    drilldown: "Разлагање",
    closeAnalysis: "Затвори разлагање",
    netBooked: "Нето књижено",
    monthlyBreakdown: "Кретање по месецима",
    breakdownMerchants: "Добављачи који чине износ",
    breakdownAccounts: "Расходни конти који чине износ",
    sourceDocuments: "Документи иза износа",
    sourceDocumentsHelp: "Сваки ред се може пратити до књиженог документа и изворног податка.",
    voucher: "Број документа",
    noVoucher: "Број документа није доступан",
    openDocument: "Отвори документ",
  },
} as const;

export function insightMixedCopy(value: string | null | undefined) {
  return copy[language(value)];
}

export function insightMixedLocale(value: string | null | undefined) {
  const lang = language(value);
  if (lang === "en") return "en-GB";
  if (lang === "pl") return "pl-PL";
  if (lang === "sr") return "sr-RS";
  return "is-IS";
}

export type InsightUnitSemanticCopy = {
  kindLabel: string;
  totalQuantity: string;
  monthlyTitle: string;
  monthlyHelp: string;
  quantityEffect: string;
  quantityChange: string;
  averagePrice: string;
};

function unitSemanticKey(unit: string) {
  if (unit === "l") return "LITRES";
  if (unit === "kg") return "WEIGHT";
  if (unit === "stk.") return "COUNT";
  if (unit === "klst.") return "HOURS";
  if (unit === "kWh") return "ENERGY";
  if (unit === "km") return "DISTANCE";
  if (unit === "m") return "LENGTH";
  if (unit === "m²") return "AREA";
  if (unit === "m³") return "VOLUME";
  return "GENERIC";
}

export function insightUnitSemanticCopy(
  value: string | null | undefined,
  unit: string,
): InsightUnitSemanticCopy {
  const lang = language(value);
  const key = unitSemanticKey(unit);

  const generic: Record<InsightMixedLanguage, InsightUnitSemanticCopy> = {
    is: {
      kindLabel: "Magn",
      totalQuantity: "Heildarmagn",
      monthlyTitle: "Magn og kostnaður eftir mánuðum",
      monthlyHelp: "Mánaðarlegt magn, línukostnaður og magnvegið meðalverð úr sömu rekjanlegu vörulínum.",
      quantityEffect: "Magnáhrif",
      quantityChange: "Breyting á magni",
      averagePrice: "Magnvegið meðalverð",
    },
    en: {
      kindLabel: "Quantity",
      totalQuantity: "Total quantity",
      monthlyTitle: "Quantity and cost by month",
      monthlyHelp: "Monthly quantity, line-item cost and quantity-weighted average price from the same traceable line items.",
      quantityEffect: "Quantity effect",
      quantityChange: "Quantity change",
      averagePrice: "Quantity-weighted average",
    },
    pl: {
      kindLabel: "Ilość",
      totalQuantity: "Łączna ilość",
      monthlyTitle: "Ilość i koszt według miesięcy",
      monthlyHelp: "Miesięczna ilość, koszt pozycji i średnia cena ważona ilością z tych samych możliwych do prześledzenia pozycji.",
      quantityEffect: "Efekt ilości",
      quantityChange: "Zmiana ilości",
      averagePrice: "Średnia ważona ilością",
    },
    sr: {
      kindLabel: "Количина",
      totalQuantity: "Укупна количина",
      monthlyTitle: "Количина и трошак по месецима",
      monthlyHelp: "Месечна количина, трошак ставки и просечна цена пондерисана количином из истих проверљивих ставки.",
      quantityEffect: "Утицај количине",
      quantityChange: "Промена количине",
      averagePrice: "Просечна цена пондерисана количином",
    },
  };

  const overrides: Partial<Record<string, Record<InsightMixedLanguage, Partial<InsightUnitSemanticCopy>>>> = {
    LITRES: {
      is: { kindLabel: "Lítrar", totalQuantity: "Heildarlítrar", monthlyTitle: "Lítrar og kostnaður eftir mánuðum", quantityEffect: "Notkunaráhrif", quantityChange: "Breyting á lítrum", averagePrice: "Lítravegið meðalverð" },
      en: { kindLabel: "Litres", totalQuantity: "Total litres", monthlyTitle: "Litres and cost by month", quantityEffect: "Usage effect", quantityChange: "Change in litres", averagePrice: "Litre-weighted average" },
      pl: { kindLabel: "Litry", totalQuantity: "Łącznie litrów", monthlyTitle: "Litry i koszt według miesięcy", quantityEffect: "Efekt zużycia", quantityChange: "Zmiana liczby litrów", averagePrice: "Średnia ważona litrami" },
      sr: { kindLabel: "Литри", totalQuantity: "Укупно литара", monthlyTitle: "Литри и трошак по месецима", quantityEffect: "Утицај потрошње", quantityChange: "Промена литара", averagePrice: "Просек пондерисан литрима" },
    },
    HOURS: {
      is: { kindLabel: "Tímar", totalQuantity: "Heildartímar", monthlyTitle: "Tímar og kostnaður eftir mánuðum", quantityEffect: "Tímaáhrif", quantityChange: "Breyting á tímum", averagePrice: "Tímavegið meðalverð" },
      en: { kindLabel: "Hours", totalQuantity: "Total hours", monthlyTitle: "Hours and cost by month", quantityEffect: "Hours effect", quantityChange: "Change in hours", averagePrice: "Hour-weighted average" },
      pl: { kindLabel: "Godziny", totalQuantity: "Łącznie godzin", monthlyTitle: "Godziny i koszt według miesięcy", quantityEffect: "Efekt czasu", quantityChange: "Zmiana liczby godzin", averagePrice: "Średnia ważona godzinami" },
      sr: { kindLabel: "Сати", totalQuantity: "Укупно сати", monthlyTitle: "Сати и трошак по месецима", quantityEffect: "Утицај сати", quantityChange: "Промена сати", averagePrice: "Просек пондерисан сатима" },
    },
    COUNT: {
      is: { kindLabel: "Stykki", totalQuantity: "Heildarfjöldi", monthlyTitle: "Fjöldi og kostnaður eftir mánuðum", quantityEffect: "Fjöldaáhrif", quantityChange: "Breyting á fjölda", averagePrice: "Fjöldavegið meðalverð" },
      en: { kindLabel: "Items", totalQuantity: "Total items", monthlyTitle: "Items and cost by month", quantityEffect: "Count effect", quantityChange: "Change in item count", averagePrice: "Count-weighted average" },
      pl: { kindLabel: "Sztuki", totalQuantity: "Łączna liczba sztuk", monthlyTitle: "Liczba sztuk i koszt według miesięcy", quantityEffect: "Efekt liczby sztuk", quantityChange: "Zmiana liczby sztuk", averagePrice: "Średnia ważona liczbą sztuk" },
      sr: { kindLabel: "Комади", totalQuantity: "Укупно комада", monthlyTitle: "Комади и трошак по месецима", quantityEffect: "Утицај броја комада", quantityChange: "Промена броја комада", averagePrice: "Просек пондерисан бројем комада" },
    },
    WEIGHT: {
      is: { kindLabel: "Þyngd", totalQuantity: "Heildarþyngd", monthlyTitle: "Þyngd og kostnaður eftir mánuðum", quantityEffect: "Þyngdaráhrif", quantityChange: "Breyting á þyngd", averagePrice: "Þyngdarvegið meðalverð" },
      en: { kindLabel: "Weight", totalQuantity: "Total weight", monthlyTitle: "Weight and cost by month", quantityEffect: "Weight effect", quantityChange: "Change in weight", averagePrice: "Weight-weighted average" },
      pl: { kindLabel: "Masa", totalQuantity: "Łączna masa", monthlyTitle: "Masa i koszt według miesięcy", quantityEffect: "Efekt masy", quantityChange: "Zmiana masy", averagePrice: "Średnia ważona masą" },
      sr: { kindLabel: "Тежина", totalQuantity: "Укупна тежина", monthlyTitle: "Тежина и трошак по месецима", quantityEffect: "Утицај тежине", quantityChange: "Промена тежине", averagePrice: "Просек пондерисан тежином" },
    },
    ENERGY: {
      is: { kindLabel: "Orka", totalQuantity: "Heildarnotkun", monthlyTitle: "Orkunotkun og kostnaður eftir mánuðum", quantityEffect: "Notkunaráhrif", quantityChange: "Breyting á notkun", averagePrice: "Notkunarvegið meðalverð" },
      en: { kindLabel: "Energy", totalQuantity: "Total usage", monthlyTitle: "Energy use and cost by month", quantityEffect: "Usage effect", quantityChange: "Change in usage", averagePrice: "Usage-weighted average" },
      pl: { kindLabel: "Energia", totalQuantity: "Łączne zużycie", monthlyTitle: "Zużycie energii i koszt według miesięcy", quantityEffect: "Efekt zużycia", quantityChange: "Zmiana zużycia", averagePrice: "Średnia ważona zużyciem" },
      sr: { kindLabel: "Енергија", totalQuantity: "Укупна потрошња", monthlyTitle: "Потрошња енергије и трошак по месецима", quantityEffect: "Утицај потрошње", quantityChange: "Промена потрошње", averagePrice: "Просек пондерисан потрошњом" },
    },
    DISTANCE: {
      is: { kindLabel: "Akstur", totalQuantity: "Heildarkílómetrar", monthlyTitle: "Akstur og kostnaður eftir mánuðum", quantityEffect: "Akstursáhrif", quantityChange: "Breyting á akstri", averagePrice: "Kílómetravegið meðalverð" },
      en: { kindLabel: "Distance", totalQuantity: "Total kilometres", monthlyTitle: "Distance and cost by month", quantityEffect: "Distance effect", quantityChange: "Change in distance", averagePrice: "Kilometre-weighted average" },
      pl: { kindLabel: "Dystans", totalQuantity: "Łączna liczba kilometrów", monthlyTitle: "Dystans i koszt według miesięcy", quantityEffect: "Efekt dystansu", quantityChange: "Zmiana dystansu", averagePrice: "Średnia ważona kilometrami" },
      sr: { kindLabel: "Километри", totalQuantity: "Укупно километара", monthlyTitle: "Километри и трошак по месецима", quantityEffect: "Утицај километраже", quantityChange: "Промена километраже", averagePrice: "Просек пондерисан километрима" },
    },
    LENGTH: {
      is: { kindLabel: "Lengd", totalQuantity: "Heildarlengd", monthlyTitle: "Lengd og kostnaður eftir mánuðum", quantityEffect: "Lengdaráhrif", quantityChange: "Breyting á lengd" },
      en: { kindLabel: "Length", totalQuantity: "Total length", monthlyTitle: "Length and cost by month", quantityEffect: "Length effect", quantityChange: "Change in length" },
      pl: { kindLabel: "Długość", totalQuantity: "Łączna długość", monthlyTitle: "Długość i koszt według miesięcy", quantityEffect: "Efekt długości", quantityChange: "Zmiana długości" },
      sr: { kindLabel: "Дужина", totalQuantity: "Укупна дужина", monthlyTitle: "Дужина и трошак по месецима", quantityEffect: "Утицај дужине", quantityChange: "Промена дужине" },
    },
    AREA: {
      is: { kindLabel: "Flatarmál", totalQuantity: "Heildarflatarmál", monthlyTitle: "Flatarmál og kostnaður eftir mánuðum", quantityEffect: "Flatarmálsáhrif", quantityChange: "Breyting á flatarmáli" },
      en: { kindLabel: "Area", totalQuantity: "Total area", monthlyTitle: "Area and cost by month", quantityEffect: "Area effect", quantityChange: "Change in area" },
      pl: { kindLabel: "Powierzchnia", totalQuantity: "Łączna powierzchnia", monthlyTitle: "Powierzchnia i koszt według miesięcy", quantityEffect: "Efekt powierzchni", quantityChange: "Zmiana powierzchni" },
      sr: { kindLabel: "Површина", totalQuantity: "Укупна површина", monthlyTitle: "Површина и трошак по месецима", quantityEffect: "Утицај површине", quantityChange: "Промена површине" },
    },
    VOLUME: {
      is: { kindLabel: "Rúmmál", totalQuantity: "Heildarrúmmál", monthlyTitle: "Rúmmál og kostnaður eftir mánuðum", quantityEffect: "Rúmmálsáhrif", quantityChange: "Breyting á rúmmáli" },
      en: { kindLabel: "Volume", totalQuantity: "Total volume", monthlyTitle: "Volume and cost by month", quantityEffect: "Volume effect", quantityChange: "Change in volume" },
      pl: { kindLabel: "Objętość", totalQuantity: "Łączna objętość", monthlyTitle: "Objętość i koszt według miesięcy", quantityEffect: "Efekt objętości", quantityChange: "Zmiana objętości" },
      sr: { kindLabel: "Запремина", totalQuantity: "Укупна запремина", monthlyTitle: "Запремина и трошак по месецима", quantityEffect: "Утицај запремине", quantityChange: "Промена запремине" },
    },
  };

  return {
    ...generic[lang],
    ...(overrides[key]?.[lang] ?? {}),
  };
}

export type InsightUnitFlowCopy = {
  totalValue: string;
  monthlyTitle: (kindLabel: string) => string;
  monthlyHelp: string;
  driverHelp: string;
  valueChange: string;
  exactNote: string;
  lineValue: string;
};

export function insightUnitFlowCopy(
  value: string | null | undefined,
  flow: "SALE" | "PURCHASE" | "UNKNOWN",
): InsightUnitFlowCopy {
  const lang = language(value);

  const byLanguage: Record<InsightMixedLanguage, Record<typeof flow, InsightUnitFlowCopy>> = {
    is: {
      SALE: {
        totalValue: "Heildartekjur",
        monthlyTitle: (kind) => `${kind} og tekjur eftir mánuðum`,
        monthlyHelp: "Mánaðarlegt magn, tekjuverðmæti línanna og magnvegið meðalverð á sama verðgrunni og einingarverðið.",
        driverHelp: "Nýjasti samfelldi mánaðarsamanburðurinn sundurgreinir tekjubreytingu í magnáhrif og verðáhrif án AI.",
        valueChange: "Tekjubreyting",
        exactNote: "Magnáhrif og verðáhrif eru reiknuð á sama verðgrunni og einingarverðið svo þau leggjast nákvæmlega saman í tekjubreytinguna. Bókhaldi og vörulínum er ekki breytt.",
        lineValue: "Línuverðmæti",
      },
      PURCHASE: {
        totalValue: "Heildarkostnaður",
        monthlyTitle: (kind) => `${kind} og kostnaður eftir mánuðum`,
        monthlyHelp: "Mánaðarlegt magn, kostnaðarverðmæti línanna og magnvegið meðalverð á sama verðgrunni og einingarverðið.",
        driverHelp: "Nýjasti samfelldi mánaðarsamanburðurinn sundurgreinir kostnaðarbreytingu í magnáhrif og verðáhrif án AI.",
        valueChange: "Kostnaðarbreyting",
        exactNote: "Magnáhrif og verðáhrif eru reiknuð á sama verðgrunni og einingarverðið svo þau leggjast nákvæmlega saman í kostnaðarbreytinguna. Bókhaldi og vörulínum er ekki breytt.",
        lineValue: "Línuverðmæti",
      },
      UNKNOWN: {
        totalValue: "Heildarlínuverðmæti",
        monthlyTitle: (kind) => `${kind} og línuverðmæti eftir mánuðum`,
        monthlyHelp: "Mánaðarlegt magn, línuverðmæti og magnvegið meðalverð á sama verðgrunni og einingarverðið.",
        driverHelp: "Nýjasti samfelldi mánaðarsamanburðurinn sundurgreinir breytingu í magnáhrif og verðáhrif án AI.",
        valueChange: "Breyting á línuverðmæti",
        exactNote: "Magnáhrif og verðáhrif eru reiknuð á sama verðgrunni og einingarverðið svo þau leggjast nákvæmlega saman. Bókhaldi og vörulínum er ekki breytt.",
        lineValue: "Línuverðmæti",
      },
    },
    en: {
      SALE: { totalValue: "Total revenue", monthlyTitle: (kind) => `${kind} and revenue by month`, monthlyHelp: "Monthly quantity, line revenue and quantity-weighted average on the same value basis as the unit price.", driverHelp: "The latest adjacent-month comparison decomposes the revenue change into quantity and price effects without AI.", valueChange: "Revenue change", exactNote: "Quantity and price effects use the same value basis as the unit price and add exactly to the revenue change. Bookkeeping and source lines are unchanged.", lineValue: "Line value" },
      PURCHASE: { totalValue: "Total cost", monthlyTitle: (kind) => `${kind} and cost by month`, monthlyHelp: "Monthly quantity, line cost and quantity-weighted average on the same value basis as the unit price.", driverHelp: "The latest adjacent-month comparison decomposes the cost change into quantity and price effects without AI.", valueChange: "Cost change", exactNote: "Quantity and price effects use the same value basis as the unit price and add exactly to the cost change. Bookkeeping and source lines are unchanged.", lineValue: "Line value" },
      UNKNOWN: { totalValue: "Total line value", monthlyTitle: (kind) => `${kind} and line value by month`, monthlyHelp: "Monthly quantity, line value and quantity-weighted average on the same value basis as the unit price.", driverHelp: "The latest adjacent-month comparison decomposes the value change into quantity and price effects without AI.", valueChange: "Line-value change", exactNote: "Quantity and price effects use the same value basis as the unit price and add exactly to the value change. Bookkeeping and source lines are unchanged.", lineValue: "Line value" },
    },
    pl: {
      SALE: { totalValue: "Łączne przychody", monthlyTitle: (kind) => `${kind} i przychody według miesięcy`, monthlyHelp: "Miesięczna ilość, wartość przychodów z pozycji i średnia ważona ilością na tej samej podstawie co cena jednostkowa.", driverHelp: "Najnowsze porównanie sąsiednich miesięcy rozkłada zmianę przychodów na efekt ilości i ceny bez AI.", valueChange: "Zmiana przychodów", exactNote: "Efekty ilości i ceny są liczone na tej samej podstawie co cena jednostkowa i dokładnie składają się na zmianę przychodów. Księgowania i pozycje źródłowe nie są zmieniane.", lineValue: "Wartość pozycji" },
      PURCHASE: { totalValue: "Łączny koszt", monthlyTitle: (kind) => `${kind} i koszt według miesięcy`, monthlyHelp: "Miesięczna ilość, koszt pozycji i średnia ważona ilością na tej samej podstawie co cena jednostkowa.", driverHelp: "Najnowsze porównanie sąsiednich miesięcy rozkłada zmianę kosztu na efekt ilości i ceny bez AI.", valueChange: "Zmiana kosztu", exactNote: "Efekty ilości i ceny są liczone na tej samej podstawie co cena jednostkowa i dokładnie składają się na zmianę kosztu. Księgowania i pozycje źródłowe nie są zmieniane.", lineValue: "Wartość pozycji" },
      UNKNOWN: { totalValue: "Łączna wartość pozycji", monthlyTitle: (kind) => `${kind} i wartość pozycji według miesięcy`, monthlyHelp: "Miesięczna ilość, wartość pozycji i średnia ważona ilością na tej samej podstawie co cena jednostkowa.", driverHelp: "Najnowsze porównanie sąsiednich miesięcy rozkłada zmianę wartości na efekt ilości i ceny bez AI.", valueChange: "Zmiana wartości pozycji", exactNote: "Efekty ilości i ceny są liczone na tej samej podstawie co cena jednostkowa i dokładnie składają się na zmianę wartości. Księgowania i pozycje źródłowe nie są zmieniane.", lineValue: "Wartość pozycji" },
    },
    sr: {
      SALE: { totalValue: "Укупан приход", monthlyTitle: (kind) => `${kind} и приход по месецима`, monthlyHelp: "Месечна количина, вредност прихода по ставкама и просек пондерисан количином на истој основи као јединична цена.", driverHelp: "Најновије поређење суседних месеци раздваја промену прихода на утицај количине и цене без AI.", valueChange: "Промена прихода", exactNote: "Утицаји количине и цене користе исту основу као јединична цена и тачно се сабирају у промену прихода. Књижење и изворне ставке се не мењају.", lineValue: "Вредност ставке" },
      PURCHASE: { totalValue: "Укупан трошак", monthlyTitle: (kind) => `${kind} и трошак по месецима`, monthlyHelp: "Месечна количина, трошак ставки и просек пондерисан количином на истој основи као јединична цена.", driverHelp: "Најновије поређење суседних месеци раздваја промену трошка на утицај количине и цене без AI.", valueChange: "Промена трошка", exactNote: "Утицаји количине и цене користе исту основу као јединична цена и тачно се сабирају у промену трошка. Књижење и изворне ставке се не мењају.", lineValue: "Вредност ставке" },
      UNKNOWN: { totalValue: "Укупна вредност ставки", monthlyTitle: (kind) => `${kind} и вредност ставки по месецима`, monthlyHelp: "Месечна количина, вредност ставки и просек пондерисан количином на истој основи као јединична цена.", driverHelp: "Најновије поређење суседних месеци раздваја промену вредности на утицај количине и цене без AI.", valueChange: "Промена вредности ставки", exactNote: "Утицаји количине и цене користе исту основу као јединична цена и тачно се сабирају у промену вредности. Књижење и изворне ставке се не мењају.", lineValue: "Вредност ставке" },
    },
  };

  return byLanguage[lang][flow];
}
