import type { BankAnalysisLanguage } from "./analysis-text";

const text = {
  is: {
    navAria: "Ársgreining – hlutar", overview: "Yfirlit", summary: "Samantekt", income: "Tekjur", expenses: "Gjöld", flows: "Peningaflæði", patterns: "Mynstur", accounts: "Reikningar",
    analysis: "Ársgreining", bridgeTitle: "Brú að ársreikningi", bridgeHelp: "Samantektin byggir á því sem bankagögnin styðja nú þegar. Hún er ekki ársreikningur og reynir ekki að laga niðurstöðuna að fyrirliggjandi ársreikningstölum. Óvissa og fjárflæði sem ekki er rekstrarkostnaður eru sýnd sérstaklega.", dataFirst: "Gögn fyrst · AI 0 kr.",
    totalInflows: "Innborganir alls", totalOutflows: "Útborganir alls", likelyTurnover: "Líkleg velta / greiðsluuppgjör", unclassifiedOutflow: "Óflokkað útstreymi", viewUnclassified: "Skoða óflokkað →",
    incomeSide: "Tekjuhlið", incomeSideHelp: "Bankagreiningin heldur rekstrartekjum, greiðsluuppgjörum og öðrum innstreymum aðskildum þar til gögn staðfesta eðli þeirra.", strongOperatingRevenue: "Sterkt merkt rekstrartekjuinnstreymi", paymentSettlement: "Greiðslumiðlunaruppgjör", grants: "Styrkir / framlög", loans: "Lán / fjármagnshreyfingar", refunds: "Endurgreiðslur", unknownInflows: "Óflokkað / óvíst innstreymi",
    expenseSide: "Gjaldahlið", expenseSideHelp: "Rekstrarkostnaður er dreginn saman, en laun, tengdar einingar og aðrir sérstakir fjárstraumar standa sér.", identifiedOperatingExpense: "Greindur rekstrarkostnaður", wages: "Laun", payrollRelated: "Launatengd gjöld", personPayments: "Greiðslur til einstaklinga", relatedEntity: "Fjárflæði til tengdrar einingar / deildar", bankFees: "Bankakostnaður", unknownOutflows: "Óflokkað útstreymi",
    operatingByNature: "Rekstrarkostnaður eftir eðli", operatingByNatureHelp: "Þetta er vinnubrú úr bankagögnum yfir í ársreikningsliði. Fylgiskjöl og bókhald geta síðar staðfest eða fært einstaka liði.", openExpenseAnalysis: "Opna gjaldagreiningu →", item: "Liður", fromBankData: "Greint úr bankagögnum", status: "Staða", bankDataOnly: "Bankagögn eingöngu", notFinalAccounts: "Ekki lokaársreikningur. Næsta staðfestingarlag er bókhald og fylgiskjöl. Þegar fyrirliggjandi ársreikningur er tengdur við greininguna má bæta við samanburði, fráviki og rekjanlegri skýringu.",
    viewWhatForms: "Skoða hvað myndar þessa tölu →", viewTransactions: "Skoða færslur →", viewTransactionsIn: "Skoða færslur í",
    insightResearch: "Rannsókn úr Innsýn", exactResearchTitle: "Nákvæmt færslusafn rannsóknaratriðis", exactResearchHelp: "Aðeins þær bankafærslur sem mynda valið rannsóknaratriði eru sýndar hér. Þetta breytir hvorki flokkun né bókun.", transactionsLabel: "færslur", date: "Dagsetning", account: "Reikningur", textLabel: "Texti", amount: "Upphæð", exactMatch: "Rannsókn úr Innsýn · nákvæm pörun", pairs: "pör",
  },
  en: {
    navAria: "Annual analysis sections", overview: "Overview", summary: "Summary", income: "Income", expenses: "Expenses", flows: "Cash flow", patterns: "Patterns", accounts: "Accounts",
    analysis: "Annual analysis", bridgeTitle: "Bridge to annual accounts", bridgeHelp: "The summary is based on what the bank data already supports. It is not an annual account and does not try to force the result to match existing annual-account figures. Uncertainty and non-operating cash flows are shown separately.", dataFirst: "Data first · AI ISK 0",
    totalInflows: "Total inflows", totalOutflows: "Total outflows", likelyTurnover: "Likely turnover / payment settlements", unclassifiedOutflow: "Unclassified outflows", viewUnclassified: "View unclassified →",
    incomeSide: "Income side", incomeSideHelp: "The bank analysis keeps operating revenue, payment settlements and other inflows separate until the evidence confirms their nature.", strongOperatingRevenue: "Strongly labelled operating-revenue inflow", paymentSettlement: "Payment settlements", grants: "Grants / contributions", loans: "Loans / capital movements", refunds: "Refunds", unknownInflows: "Unclassified / uncertain inflows",
    expenseSide: "Expense side", expenseSideHelp: "Operating expenses are summarized, while wages, related entities and other special cash flows remain separate.", identifiedOperatingExpense: "Identified operating expenses", wages: "Wages", payrollRelated: "Payroll-related costs", personPayments: "Payments to individuals", relatedEntity: "Flow to related entity / department", bankFees: "Bank fees", unknownOutflows: "Unclassified outflows",
    operatingByNature: "Operating expenses by nature", operatingByNatureHelp: "This is a working bridge from bank data to annual-account line items. Receipts and bookkeeping can later confirm or reclassify individual items.", openExpenseAnalysis: "Open expense analysis →", item: "Item", fromBankData: "Identified from bank data", status: "Status", bankDataOnly: "Bank data only", notFinalAccounts: "Not final annual accounts. The next confirmation layer is bookkeeping and source documents. When an existing annual account is linked to the analysis, comparison, variance and traceable explanations can be added.",
    viewWhatForms: "View what forms this amount →", viewTransactions: "View transactions →", viewTransactionsIn: "View transactions in",
    insightResearch: "Research from Insights", exactResearchTitle: "Exact transaction set for the research item", exactResearchHelp: "Only the bank transactions that form the selected research item are shown here. This changes neither classification nor booking.", transactionsLabel: "transactions", date: "Date", account: "Account", textLabel: "Text", amount: "Amount", exactMatch: "Research from Insights · exact matching", pairs: "pairs",
  },
  pl: {
    navAria: "Sekcje analizy rocznej", overview: "Przegląd", summary: "Podsumowanie", income: "Wpływy", expenses: "Wydatki", flows: "Przepływy", patterns: "Wzorce", accounts: "Rachunki",
    analysis: "Analiza roczna", bridgeTitle: "Pomost do sprawozdania rocznego", bridgeHelp: "Podsumowanie opiera się na tym, co już potwierdzają dane bankowe. Nie jest to sprawozdanie roczne i nie próbuje dopasować wyniku do istniejących liczb ze sprawozdania. Niepewność i przepływy nieoperacyjne są pokazane osobno.", dataFirst: "Najpierw dane · AI 0 ISK",
    totalInflows: "Łączne wpływy", totalOutflows: "Łączne wypływy", likelyTurnover: "Prawdopodobny obrót / rozliczenia płatności", unclassifiedOutflow: "Niesklasyfikowane wypływy", viewUnclassified: "Pokaż niesklasyfikowane →",
    incomeSide: "Strona przychodowa", incomeSideHelp: "Analiza bankowa oddziela przychody operacyjne, rozliczenia płatności i inne wpływy, dopóki dane nie potwierdzą ich charakteru.", strongOperatingRevenue: "Silnie oznaczone wpływy operacyjne", paymentSettlement: "Rozliczenia płatności", grants: "Dotacje / wkłady", loans: "Pożyczki / przepływy kapitałowe", refunds: "Zwroty", unknownInflows: "Niesklasyfikowane / niepewne wpływy",
    expenseSide: "Strona kosztowa", expenseSideHelp: "Koszty operacyjne są agregowane, natomiast płace, jednostki powiązane i inne szczególne przepływy pozostają osobno.", identifiedOperatingExpense: "Rozpoznane koszty operacyjne", wages: "Płace", payrollRelated: "Koszty związane z płacami", personPayments: "Płatności na rzecz osób fizycznych", relatedEntity: "Przepływ do powiązanej jednostki / sekcji", bankFees: "Koszty bankowe", unknownOutflows: "Niesklasyfikowane wypływy",
    operatingByNature: "Koszty operacyjne według rodzaju", operatingByNatureHelp: "To roboczy pomost z danych bankowych do pozycji sprawozdania rocznego. Dokumenty źródłowe i księgowość mogą później potwierdzić lub przenieść poszczególne pozycje.", openExpenseAnalysis: "Otwórz analizę wydatków →", item: "Pozycja", fromBankData: "Rozpoznane z danych bankowych", status: "Status", bankDataOnly: "Tylko dane bankowe", notFinalAccounts: "To nie jest końcowe sprawozdanie roczne. Następną warstwą potwierdzenia są księgowość i dokumenty źródłowe. Po połączeniu istniejącego sprawozdania można dodać porównanie, odchylenia i możliwe do prześledzenia wyjaśnienia.",
    viewWhatForms: "Pokaż, co tworzy tę kwotę →", viewTransactions: "Pokaż transakcje →", viewTransactionsIn: "Pokaż transakcje w",
    insightResearch: "Badanie z Analiz", exactResearchTitle: "Dokładny zestaw transakcji dla elementu badania", exactResearchHelp: "Pokazane są tylko transakcje bankowe tworzące wybrany element badania. Nie zmienia to klasyfikacji ani księgowania.", transactionsLabel: "transakcji", date: "Data", account: "Rachunek", textLabel: "Tekst", amount: "Kwota", exactMatch: "Badanie z Analiz · dokładne dopasowanie", pairs: "par",
  },
  sr: {
    navAria: "Одељци годишње анализе", overview: "Преглед", summary: "Сажетак", income: "Приливи", expenses: "Расходи", flows: "Новчани ток", patterns: "Обрасци", accounts: "Рачуни",
    analysis: "Годишња анализа", bridgeTitle: "Мост ка годишњем извештају", bridgeHelp: "Сажетак се заснива на ономе што банкарски подаци већ подржавају. Ово није годишњи извештај и не покушава да прилагоди резултат постојећим бројевима из извештаја. Неизвесност и неоперативни токови новца приказани су одвојено.", dataFirst: "Прво подаци · AI 0 ISK",
    totalInflows: "Укупни приливи", totalOutflows: "Укупни одливи", likelyTurnover: "Вероватан промет / платна поравнања", unclassifiedOutflow: "Некласификовани одливи", viewUnclassified: "Прикажи некласификовано →",
    incomeSide: "Приходна страна", incomeSideHelp: "Банкарска анализа држи оперативне приходе, платна поравнања и друге приливе одвојено док подаци не потврде њихову природу.", strongOperatingRevenue: "Јасно означени оперативни приливи", paymentSettlement: "Платна поравнања", grants: "Дотације / доприноси", loans: "Зајмови / капитална кретања", refunds: "Повраћаји", unknownInflows: "Некласификовани / неизвесни приливи",
    expenseSide: "Расходна страна", expenseSideHelp: "Оперативни расходи се сабирају, док зараде, повезани субјекти и други посебни токови остају одвојени.", identifiedOperatingExpense: "Препознати оперативни расходи", wages: "Зараде", payrollRelated: "Трошкови повезани са зарадама", personPayments: "Исплате физичким лицима", relatedEntity: "Ток ка повезаном субјекту / одељењу", bankFees: "Банкарски трошкови", unknownOutflows: "Некласификовани одливи",
    operatingByNature: "Оперативни расходи по природи", operatingByNatureHelp: "Ово је радни мост од банкарских података до ставки годишњег извештаја. Изворна документа и књиговодство касније могу потврдити или прекласификовати појединачне ставке.", openExpenseAnalysis: "Отвори анализу расхода →", item: "Ставка", fromBankData: "Препознато из банкарских података", status: "Статус", bankDataOnly: "Само банкарски подаци", notFinalAccounts: "Ово није коначни годишњи извештај. Следећи слој потврде су књиговодство и изворна документа. Када се постојећи годишњи извештај повеже са анализом, могу се додати поређење, одступања и следљива објашњења.",
    viewWhatForms: "Прикажи шта чини овај износ →", viewTransactions: "Прикажи трансакције →", viewTransactionsIn: "Прикажи трансакције у",
    insightResearch: "Истраживање из Увида", exactResearchTitle: "Тачан скуп трансакција за истраживачку ставку", exactResearchHelp: "Овде су приказане само банкарске трансакције које чине изабрану истраживачку ставку. Ово не мења ни класификацију ни књижење.", transactionsLabel: "трансакција", date: "Датум", account: "Рачун", textLabel: "Текст", amount: "Износ", exactMatch: "Истраживање из Увида · тачно подударање", pairs: "парова",
  },
} as const;

export function annualAnalysisExtraText(language: BankAnalysisLanguage) {
  return text[language] ?? text.is;
}
