type Language = "is" | "en";

const texts = {
  is: {
    title: "Verk 10",
    description: "Tilraunaumhverfi fyrir nýja Verk-kjarnann. Núverandi /verk er ósnert.",
    safeMode: "Öruggur reynsluakstur",
    safeModeText: "Þessi fyrsta útgáfa les núverandi Verk-gögn en skrifar engu nýju í gagnagrunninn.",
    oldWork: "Opna núverandi Verk",
    allWorks: "Öll verk",
    inProgress: "Í vinnu",
    completed: "Lokið",
    workList: "Verk til reynsluaksturs",
    open: "Opna",
    noWorks: "Engin verk fundust í virku fyrirtæki.",
    currentFacts: "Núverandi staðreyndir",
    workParts: "Verkþættir",
    assignments: "Úthlutun og auðlindir",
    usage: "Raunnotkun",
    effects: "Afleiðingar",
    notStoredYet: "Ekki vistað í nýja domain-líkaninu enn.",
    workNumber: "Verknúmer",
    workKey: "Verklykill",
    status: "Staða",
    priority: "Forgangur",
    address: "Staðsetning",
    descriptionLabel: "Lýsing",
    workHistory: "Núverandi tímaskráningar",
    noLogs: "Engar tímaskráningar eru á verkinu.",
    back: "Til baka í Verk 10",
    compareOld: "Samanburður: opna gamla Verk",
    minutes: "mín.",
    unknown: "Ekki skráð",
  },
  en: {
    title: "Work 10",
    description: "Experimental workspace for the new Work core. Existing /verk remains untouched.",
    safeMode: "Safe test drive",
    safeModeText: "This first version reads existing Work data but writes no new data to the database.",
    oldWork: "Open current Work",
    allWorks: "All work",
    inProgress: "In progress",
    completed: "Completed",
    workList: "Work items for test driving",
    open: "Open",
    noWorks: "No work items were found for the active company.",
    currentFacts: "Current facts",
    workParts: "Work parts",
    assignments: "Assignments and resources",
    usage: "Actual usage",
    effects: "Effects",
    notStoredYet: "Not stored in the new domain model yet.",
    workNumber: "Work number",
    workKey: "Work key",
    status: "Status",
    priority: "Priority",
    address: "Location",
    descriptionLabel: "Description",
    workHistory: "Current time logs",
    noLogs: "No time logs exist for this work item.",
    back: "Back to Work 10",
    compareOld: "Compare: open current Work",
    minutes: "min.",
    unknown: "Not recorded",
  },
} as const;

export function work10Text(language?: string) {
  const normalized: Language = language === "en" ? "en" : "is";
  return texts[normalized];
}
