import { redirect } from "next/navigation";
import BackNavigationRefresh from "@/components/BackNavigationRefresh";
import TopClock from "@/components/TopClock";
import { cookies } from "next/headers";
import { prisma } from "@/lib/prisma";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { getCompanyModuleSettings } from "@/lib/core/company-module-repository";
import { getEnabledCompanyModules } from "@/lib/core/company-modules";
import { clearActiveUser } from "@/app/actions/userActions";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const sessionToken = cookieStore.get("sessionToken")?.value;

const session = sessionToken
  ? await prisma.session.findUnique({
      where: {
        token: sessionToken,
      },
      include: {
        user: true,
      },
    })
  : null;
const activeCompanyId = cookieStore.get("activeCompanyId")?.value;


const activeUserId = cookieStore.get("activeUserId")?.value;

const sessionUser =
  session &&
  session.expiresAt >= new Date() &&
  session.user.isActive
    ? session.user
    : null;

const activeUser =
  sessionUser?.role === "ADMIN" && activeUserId
    ? await prisma.user.findUnique({
        where: {
          id: Number(activeUserId),
        },
        select: {
          id: true,
          role: true,
          isActive: true,
        },
      })
    : sessionUser;

const activeCompany =
  activeCompanyId && activeUser
    ? await prisma.company.findFirst({
        where: {
          id: Number(activeCompanyId),
          ...(activeUser.role !== "ADMIN"
            ? {
                users: {
                  some: {
                    userId: activeUser.id,
                    isActive: true,
                  },
                },
              }
            : {}),
        },
        select: {
          id: true,
          name: true,
        },
      })
    : null;

    const activeCompanyAccess =
  activeCompanyId && activeUser && activeUser.role !== "ADMIN"
    ? await prisma.userCompany.findUnique({
        where: {
          userId_companyId: {
            userId: activeUser.id,
            companyId: Number(activeCompanyId),
          },
        },
        select: {
          accessRole: true,
        },
      })
    : null;

const moduleSettings = activeCompany
  ? await getCompanyModuleSettings(activeCompany.id)
  : {};

const enabledModuleIds = getEnabledCompanyModules(moduleSettings).map(
  (module) => module.id,
);

  return (
    <html
      lang="is"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <BackNavigationRefresh />
        <div className="flex min-h-screen">

        {activeUserId && (
  <form
    action={clearActiveUser}
    className="fixed right-4 top-4 z-50"
  >
    <button
      type="submit"
      className="rounded bg-slate-800 px-4 py-2 text-sm font-medium text-white shadow hover:bg-slate-900"
    >
      Til baka í admin
    </button>
  </form>
)}
          
  <Sidebar

  activeCompanyName={activeCompany?.name ?? null}
  activeUserRole={activeUser?.role ?? "ADMIN"}
  activeCompanyRole={activeCompanyAccess?.accessRole ?? null}
  enabledModuleIds={enabledModuleIds}
/>

          <main className="flex-1">
  <TopClock />
  {children}
</main>
        </div>
      </body>
    </html>
  );
}
