export type VatGeneralPeriod = "JAN_FEB" | "MAR_APR" | "MAY_JUN" | "JUL_AUG" | "SEP_OCT" | "NOV_DEC";
const PERIODS: Record<VatGeneralPeriod,{startMonth:number;endMonth:number}> = {JAN_FEB:{startMonth:0,endMonth:1},MAR_APR:{startMonth:2,endMonth:3},MAY_JUN:{startMonth:4,endMonth:5},JUL_AUG:{startMonth:6,endMonth:7},SEP_OCT:{startMonth:8,endMonth:9},NOV_DEC:{startMonth:10,endMonth:11}};
export const VAT_GENERAL_PERIODS=Object.keys(PERIODS) as VatGeneralPeriod[];
function easterSunday(year:number){const a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31),day=((h+l-7*m+114)%31)+1;return new Date(year,month-1,day,12);}
function addDays(d:Date,n:number){const x=new Date(d);x.setDate(x.getDate()+n);return x;} function sameDay(a:Date,b:Date){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();}
function firstMondayOfAugust(year:number){const d=new Date(year,7,1,12);while(d.getDay()!==1)d.setDate(d.getDate()+1);return d;} function firstDayOfSummer(year:number){const d=new Date(year,3,19,12);while(d.getDay()!==4)d.setDate(d.getDate()+1);return d;}
function isIcelandicPublicHoliday(d:Date){const y=d.getFullYear(),fixed=[[0,1],[4,1],[5,17],[11,25],[11,26]] as const;if(fixed.some(([m,day])=>d.getMonth()===m&&d.getDate()===day))return true;const e=easterSunday(y);return [-3,-2,1,39,50].some(n=>sameDay(d,addDays(e,n)))||sameDay(d,firstDayOfSummer(y))||sameDay(d,firstMondayOfAugust(y));}
export function nextIcelandicBusinessDay(date:Date){const d=new Date(date);while(d.getDay()===0||d.getDay()===6||isIcelandicPublicHoliday(d))d.setDate(d.getDate()+1);return d;}
export function vatGeneralPeriodDates(year:number,period:VatGeneralPeriod){const p=PERIODS[period];return {start:new Date(year,p.startMonth,1,12),end:new Date(year,p.endMonth+1,0,12)};}
export function vatGeneralDueDate(year:number,period:VatGeneralPeriod){const {end}=vatGeneralPeriodDates(year,period);return nextIcelandicBusinessDay(new Date(end.getFullYear(),end.getMonth()+2,5,12));}
export function nextVatGeneralPeriod(year:number,period:VatGeneralPeriod){const i=VAT_GENERAL_PERIODS.indexOf(period);return i===VAT_GENERAL_PERIODS.length-1?{year:year+1,period:VAT_GENERAL_PERIODS[0]}:{year,period:VAT_GENERAL_PERIODS[i+1]};}
export function periodCodeFromDates(start:Date,end:Date):VatGeneralPeriod|null{for(const code of VAT_GENERAL_PERIODS){const p=PERIODS[code];if(start.getMonth()===p.startMonth&&end.getMonth()===p.endMonth)return code;}return null;}
